Repository parimalvfx/Quora, pull requests merged in 2018-10, with the labels that each got.

#20 Revert "Get User Details"
  .idea/compiler.xml
  .idea/workspace.xml
  pom.xml
  quora-api/quora-api.iml
  quora-api/src/main/java/com/upgrad/quora/api/controller/UserDetailController.java
  quora-api/target/classes/com/upgrad/quora/api/QuoraApiApplication.class
  quora-api/target/generated-sources/com/upgrad/quora/api/model/UserDetailsResponse.java
  quora-db/quora-db.iml
  quora-service/quora-service.iml
  quora-service/src/main/java/com/upgrad/quora/service/business/UserBusinessService.java
  quora-service/src/main/java/com/upgrad/quora/service/dao/UserDao.java
  quora-service/src/main/java/com/upgrad/quora/service/entity/UserAuthEntity.java
  quora-service/src/main/java/com/upgrad/quora/service/entity/UserEntity.java
  quora-service/target/classes/com/upgrad/quora/service/business/JwtTokenProvider.class
  quora-service/target/classes/com/upgrad/quora/service/business/PasswordCryptographyProvider.class
  quora-service/target/classes/com/upgrad/quora/service/business/UserBusinessService.class
  quora-service/target/classes/com/upgrad/quora/service/common/GenericErrorCode.class
  quora-service/target/classes/com/upgrad/quora/service/common/UnexpectedException.class
  quora-service/target/classes/com/upgrad/quora/service/dao/UserDao.class
  quora-service/target/classes/com/upgrad/quora/service/entity/UserEntity.class
  quora-service/target/classes/com/upgrad/quora/service/exception/AnswerNotFoundException.class
  quora-service/target/classes/com/upgrad/quora/service/exception/AuthenticationFailedException.class
  quora-service/target/classes/com/upgrad/quora/service/exception/AuthorizationFailedException.class
  quora-service/target/classes/com/upgrad/quora/service/exception/InvalidQuestionException.class
  quora-service/target/classes/com/upgrad/quora/service/exception/SignOutRestrictedException.class
  quora-service/target/classes/com/upgrad/quora/service/exception/SignUpRestrictedException.class
  quora-service/target/classes/com/upgrad/quora/service/exception/UserNotFoundException.class
Labels: invalid

#22 REST API endpoint: editQuestionContent - "/question/edit/{questionId}"
  quora-api/src/main/java/com/upgrad/quora/api/controller/QuestionController.java
  quora-api/src/main/java/com/upgrad/quora/api/exception/RestExceptionHandler.java
  quora-service/src/main/java/com/upgrad/quora/service/business/QuestionBusinessService.java
  quora-service/src/main/java/com/upgrad/quora/service/dao/QuestionDao.java
  quora-service/src/main/java/com/upgrad/quora/service/entity/QuestionEntity.java
Labels: enhancement

#21 Admin controller user delete
  quora-api/src/main/java/com/upgrad/quora/api/controller/AdminController.java
  quora-api/src/main/java/com/upgrad/quora/api/exception/RestExceptionHandler.java
  quora-service/src/main/java/com/upgrad/quora/service/business/AdminBusinessService.java
  quora-service/src/main/java/com/upgrad/quora/service/dao/UserDao.java
  quora-service/src/main/java/com/upgrad/quora/service/entity/UserEntity.java
Labels: enhancement

#25 Question controller delete question
  .idea/libraries/Java_EE_6_Java_EE_6.xml
  .idea/workspace.xml
  quora-api/src/main/java/com/upgrad/quora/api/controller/QuestionController.java
  quora-service/src/main/java/com/upgrad/quora/service/business/QuestionBusinessService.java
  quora-service/src/main/java/com/upgrad/quora/service/dao/QuestionDao.java
  quora-service/src/main/java/com/upgrad/quora/service/dao/UserDao.java
Labels: enhancement

#24 Question controller get all questions by user
  .idea/workspace.xml
  quora-api/src/main/java/com/upgrad/quora/api/controller/QuestionController.java
  quora-service/src/main/java/com/upgrad/quora/service/business/QuestionBusinessService.java
  quora-service/src/main/java/com/upgrad/quora/service/dao/QuestionDao.java
  quora-service/src/main/java/com/upgrad/quora/service/dao/UserDao.java
  quora-service/src/main/java/com/upgrad/quora/service/entity/QuestionEntity.java
Labels: enhancement

#26 Answer controller delete answer
  .idea/workspace.xml
  quora-api/src/main/java/com/upgrad/quora/api/controller/AnswerController.java
  quora-service/src/main/java/com/upgrad/quora/service/business/AnswerBusinessService.java
  quora-service/src/main/java/com/upgrad/quora/service/business/QuestionBusinessService.java
  quora-service/src/main/java/com/upgrad/quora/service/dao/AnswerDao.java
  quora-service/src/main/java/com/upgrad/quora/service/dao/QuestionDao.java
  quora-service/src/main/java/com/upgrad/quora/service/dao/UserDao.java
  quora-service/src/main/java/com/upgrad/quora/service/entity/AnswerEntity.java
Labels: enhancement

#28 Answer controller get all answers to question
  .idea/workspace.xml
  quora-api/src/main/java/com/upgrad/quora/api/controller/AnswerController.java
  quora-service/src/main/java/com/upgrad/quora/service/business/AnswerBusinessService.java
  quora-service/src/main/java/com/upgrad/quora/service/dao/AnswerDao.java
  quora-service/src/main/java/com/upgrad/quora/service/entity/AnswerEntity.java
Labels: enhancement

#31 REST API endpoint: getAllQuestions - "/question/all"
  quora-api/src/main/java/com/upgrad/quora/api/controller/QuestionController.java
  quora-service/src/main/java/com/upgrad/quora/service/business/QuestionBusinessService.java
  quora-service/src/main/java/com/upgrad/quora/service/dao/QuestionDao.java
  quora-service/src/main/java/com/upgrad/quora/service/entity/QuestionEntity.java
Labels: enhancement

#32 REST API endpoint: userProfile - "/userprofile/{userId}"
  quora-api/src/main/java/com/upgrad/quora/api/controller/CommonController.java
  quora-service/src/main/java/com/upgrad/quora/service/business/UserBusinessService.java
Labels: enhancement

#33 Updated code to pass all unit tests
  quora-api/src/main/java/com/upgrad/quora/api/controller/AnswerController.java
  quora-api/src/main/java/com/upgrad/quora/api/controller/QuestionController.java
  quora-api/src/main/java/com/upgrad/quora/api/exception/RestExceptionHandler.java
  quora-api/src/test/java/com/upgrad/quora/api/controller/AdminControllerTest.java
  quora-api/src/test/java/com/upgrad/quora/api/controller/AnswerControllerTest.java
  quora-api/src/test/java/com/upgrad/quora/api/controller/CommonControllerTest.java
  quora-api/src/test/java/com/upgrad/quora/api/controller/QuestionControllerTest.java
  quora-api/src/test/java/com/upgrad/quora/api/controller/UserControllerTest.java
  quora-service/src/main/java/com/upgrad/quora/service/business/AdminBusinessService.java
Labels: bug

#34 Minor code refactoring for submission
  quora-api/src/main/java/com/upgrad/quora/api/controller/AdminController.java
  quora-api/src/main/java/com/upgrad/quora/api/controller/AnswerController.java
  quora-api/src/main/java/com/upgrad/quora/api/controller/CommonController.java
  quora-api/src/main/java/com/upgrad/quora/api/controller/QuestionController.java
  quora-api/src/main/java/com/upgrad/quora/api/controller/UserController.java
  quora-service/src/main/java/com/upgrad/quora/service/business/AdminBusinessService.java
  quora-service/src/main/java/com/upgrad/quora/service/business/AnswerBusinessService.java
  quora-service/src/main/java/com/upgrad/quora/service/business/AuthenticationService.java
  quora-service/src/main/java/com/upgrad/quora/service/business/QuestionBusinessService.java
  quora-service/src/main/java/com/upgrad/quora/service/business/UserBusinessService.java
  quora-service/src/main/java/com/upgrad/quora/service/dao/QuestionDao.java
  quora-service/src/main/java/com/upgrad/quora/service/dao/UserDao.java
  quora-service/src/main/java/com/upgrad/quora/service/entity/QuestionEntity.java
  quora-service/src/main/java/com/upgrad/quora/service/entity/UserAuthEntity.java
  quora-service/src/main/java/com/upgrad/quora/service/entity/UserEntity.java
Labels: enhancement
